// Data names have been updated to match the 'nam' property in the GeoJSON file exactly.
export const prefectureData = [
  { name: '北海道', value: 5, memo: "aaaaa" },
  { name: 'Aomori Ken', value: 200 },
  { name: 'Iwate Ken', value: 250 },
  { name: 'Miyagi Ken', value: 300 },
  { name: 'Akita Ken', value: 180 },
  { name: 'Yamagata Ken', value: 220 },
  { name: 'Fukushima Ken', value: 280 },
  { name: 'Ibaraki Ken', value: 800 },
  { name: 'Tochigi Ken', value: 600 },
  { name: 'Gumma Ken', value: 650 }, // Note: GeoJSON uses 'Gumma'
  { name: 'Saitama Ken', value: 1500 },
  { name: 'Chiba Ken', value: 1200 },
  { name: 'Tokyo To', value: 5000 }, // Note: GeoJSON uses 'Tokyo To'
  { name: 'Kanagawa Ken', value: 2000 },
  { name: 'Niigata Ken', value: 500 },
  { name: 'Toyama Ken', value: 450 },
  { name: 'Ishikawa Ken', value: 480 },
  { name: 'Fukui Ken', value: 400 },
  { name: 'Yamanashi Ken', value: 550 },
  { name: 'Nagano Ken', value: 480 },
  { name: 'Gifu Ken', value: 600 },
  { name: 'Shizuoka Ken', value: 900 },
  { name: 'Aichi Ken', value: 1800 },
  { name: 'Mie Ken', value: 700 },
  { name: 'Shiga Ken', value: 650 },
  { name: 'Kyoto Fu', value: 1000 }, // Note: GeoJSON uses 'Kyoto Fu'
  { name: 'Osaka Fu', value: 3000 }, // Note: GeoJSON uses 'Osaka Fu'
  { name: 'Hyogo Ken', value: 1200 },
  { name: 'Nara Ken', value: 550 },
  { name: 'Wakayama Ken', value: 400 },
  { name: 'Tottori Ken', value: 300 },
  { name: 'Shimane Ken', value: 250 },
  { name: 'Okayama Ken', value: 700 },
  { name: 'Hiroshima Ken', value: 900 },
  { name: 'Yamaguchi Ken', value: 500 },
  { name: 'Tokushima Ken', value: 400 },
  { name: 'Kagawa Ken', value: 600 },
  { name: 'Ehime Ken', value: 550 },
  { name: 'Kochi Ken', value: 350 },
  { name: 'Fukuoka Ken', value: 1600 },
  { name: 'Saga Ken', value: 450 },
  { name: 'Nagasaki Ken', value: 500 },
  { name: 'Kumamoto Ken', value: 650 },
  { name: 'Oita Ken', value: 500 },
  { name: 'Miyazaki Ken', value: 400 },
  { name: 'Kagoshima Ken', value: 450 },
  { name: 'Okinawa Ken', value: 800 },
];